# .github/ISSUE_TEMPLATE/06-hydrolocations.yml
# Defines a GitHub Issue Form so your "Map Item Error Report" shows up under "New issue".

name: "Map Error: Hydrolocations"
description: "Report issues with hydrolocations."
title: "[Map Error] <item-identifier> Hydrolocations"
labels:
  - map-error-hydrolocations
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a map item error!
        Please provide the required details below.
        The title will be automatically updated based on the Item Identifier.
        Use this map to identify the item: [Map](https://spatial.dev.water.noaa.gov/view/hydrofabric).
  - type: input
    id: item-identifier
    attributes:
      label: "Item Identifier"
      description: "The hydrolocation id (e.g., poi_id 3366)."
      placeholder: "poi_id 3366"
    validations:
      required: true
  - type: input
    id: vpu
    attributes:
      label: "VPU"
      description: "The VPU where the issue occurs (e.g., 01)."
      placeholder: "01"
  - type: dropdown
    id: issue-type
    attributes:
      label: "Issue Type"
      description: "Select the type of issue."
      options:
        - hydrolocation issue
        - other
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: "Describe the issue"
      description: "Provide a summary of the issue."
      placeholder: "E.g., this hydrolocation is incorrect."
    validations:
      required: true