# .github/ISSUE_TEMPLATE/report-map-error.yml
# Defines a GitHub Issue Form so your "Map Item Error Report" shows up under "New issue".

name: "Map Item Error Report"
description: "Report an error on a map item by its identifier."
title: "[Map Error] Report" # Kept this title exactly as requested
labels:
  - map-error
body:
  - type: markdown
    attributes:
      # Added text block mentioning not to change the title
      value: |
        Thanks for reporting a map item error!
        Please provide the required details below.

        **Important:** Please do not change the automatically set title "[Map Error] Report]".
        This helps us categorize the reports efficiently.

  - type: input
    id: item-identifier
    attributes:
      label: "Item Identifier"
      description: "The common ID of the item on the map (e.g. POI-123)."
      placeholder: "POI-123"
    validations:
      required: true # Added validation - highly recommended for identifiers

  - type: textarea
    id: issue-description
    attributes:
      label: "Describe the issue"
      description: "What’s wrong with this item?"
      placeholder: "E.g. pin is offset 200 m north of actual location."
    validations:
      required: true # Added validation - the description is usually required