# .github/ISSUE_TEMPLATE/report-map-error.yml
# Defines a GitHub Issue Form so your "Map Item Error Report" shows up under "New issue".

name: "Map Item Error Report"
description: "Report an error on a map item by its identifier."
# The issue title will be prefixed with [Map Error] and include the item identifier from the form
title: "[Map Error] {{item-identifier}}"
labels:
  - map-error # Automatically adds the 'map-error' label to categorize these issues
body:
  # This defines the first field in the form
  - type: input # A single-line text input field
    id: item-identifier # Unique ID for this field, used internally and in the issue body comment
    attributes:
      label: "Item Identifier" # The visible label for the field
      description: "The common ID of the item on the map (e.g. POI-123)." # Help text
      placeholder: "POI-123" # Example text shown in the field

  # This defines the second field in the form
  - type: textarea # A multi-line text area field
    id: issue-description # Unique ID for this field
    attributes:
      label: "Describe the issue" # Visible label
      description: "What’s wrong with this item?" # Help text
      placeholder: "E.g. pin is offset 200 m north of actual location." # Example text
