name: "Export Map-Error Reports to CSV"

# Manually trigger or run on schedule
on:
  workflow_dispatch:       # add to the the Actions tab

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub pandas

      # Export issues to CSV
      - name: Export "map-error" issues to CSV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}    
        run: |
          mkdir -p .github/scripts
          python .github/scripts/export_map_errors.py \
            --label map-error \
            --output map-error-reports.csv

      # Upload the CSV as an artifact
      - name: Upload CSV
        uses: actions/upload-artifact@v3
        with:
          name: map-error-reports
          path: map-error-reports.csv