# .github/workflows/export-map-errors.yml
# Uses built-in GITHUB_TOKEN; no need to set a custom token for public repos

name: Map Error Workflows

on:
  issues:
    types: [opened]
  workflow_dispatch:

permissions:
  issues: write

jobs:
  update_title:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body;
            const regex = /### Item Identifier\n\n(.+?)\n\n/;
            const match = body.match(regex);
            if (match) {
              const itemIdentifier = match[1].trim();
              const newTitle = `[Map Error] ${itemIdentifier}`;
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                title: newTitle
              });
            }

  export:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      - name: Export "map-error" issues to CSV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          python .github/scripts/export_map_errors.py \
            --label map-error \
            --output map-error-reports.csv
      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: map-error-reports
          path: map-error-reports.csv